Bugfix: Email addresses should be case insensitive
When the same email address is used multiple times across different messages and is cased differently,
Cluegetter would throw a panic showing:
> panic: Could not execute QuotaInsertDeducedQuotaStmt in quotasGetRegexCounts().
> Error: Error 1062: Duplicate entry 'recipient-localpart@domain-4' for key 'selector'

By lowercasing all email addresses this problem was fixed